name: my-ci
on: [push]
jobs:
  build:
    name: job-build-name
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: install -g
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: execute main.js with node.js
      run: node main.js
    - name: compile css
      run: gulp css
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: _site

